// <auto-generated />
using System;
using AutoChefSystem.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoChefSystem.Repositories.Migrations
{
    [DbContext(typeof(AutoChefSystemContext))]
    [Migration("20250327145158_AddIsActiveColumn")]
    partial class AddIsActiveColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA49726A610A3");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("RobotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__C3905BCFCF563AD0");

                    b.HasIndex("LocationId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RobotId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeId")
                        .HasName("PK__Recipe__FDD988B070C73FCA");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RecipeStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("StepDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("StepId")
                        .HasName("PK__RecipeSt__24343357B09B0472");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeStep", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Robot", b =>
                {
                    b.Property<int>("RobotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RobotId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("RobotTypeId")
                        .HasColumnType("int");

                    b.HasKey("RobotId")
                        .HasName("PK__Robot__FBB3324148DE6123");

                    b.HasIndex("LocationId");

                    b.HasIndex("RobotTypeId");

                    b.ToTable("Robot", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RobotOperationLog", b =>
                {
                    b.Property<int>("RobotOperationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RobotOperationLogId"));

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("OperationLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("RobotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("RobotOperationLogId")
                        .HasName("PK__RobotOpe__19FE31E8F59DCC6F");

                    b.HasIndex("OrderId");

                    b.HasIndex("RobotId");

                    b.ToTable("RobotOperationLog", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RobotStepTask", b =>
                {
                    b.Property<int>("StepTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepTaskId"));

                    b.Property<TimeOnly>("EstimatedTime")
                        .HasColumnType("time");

                    b.Property<int>("RepeatCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TaskOrder")
                        .HasColumnType("int");

                    b.HasKey("StepTaskId")
                        .HasName("PK__RobotSte__45192A89670340D3");

                    b.HasIndex("StepId");

                    b.ToTable("RobotStepTask", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RobotType", b =>
                {
                    b.Property<int>("RobotTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RobotTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RobotTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RobotTypeId")
                        .HasName("PK__RobotTyp__B4BB3C4D0B11CC04");

                    b.ToTable("RobotType", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1AA8C07C01");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C449E6D91");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Order", b =>
                {
                    b.HasOne("AutoChefSystem.Repositories.Entities.Location", "Location")
                        .WithMany("Orders")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Location");

                    b.HasOne("AutoChefSystem.Repositories.Entities.Recipe", "Recipe")
                        .WithMany("Orders")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Recipe");

                    b.HasOne("AutoChefSystem.Repositories.Entities.Robot", "Robot")
                        .WithMany("Orders")
                        .HasForeignKey("RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Robot");

                    b.Navigation("Location");

                    b.Navigation("Recipe");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RecipeStep", b =>
                {
                    b.HasOne("AutoChefSystem.Repositories.Entities.Recipe", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeStep_Recipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Robot", b =>
                {
                    b.HasOne("AutoChefSystem.Repositories.Entities.Location", "Location")
                        .WithMany("Robots")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Robot_Location");

                    b.HasOne("AutoChefSystem.Repositories.Entities.RobotType", "RobotType")
                        .WithMany("Robots")
                        .HasForeignKey("RobotTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Robot_RobotType");

                    b.Navigation("Location");

                    b.Navigation("RobotType");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RobotOperationLog", b =>
                {
                    b.HasOne("AutoChefSystem.Repositories.Entities.Order", "Order")
                        .WithMany("RobotOperationLogs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotOperationLog_Order");

                    b.HasOne("AutoChefSystem.Repositories.Entities.Robot", "Robot")
                        .WithMany("RobotOperationLogs")
                        .HasForeignKey("RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotOperationLog_Robot");

                    b.Navigation("Order");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RobotStepTask", b =>
                {
                    b.HasOne("AutoChefSystem.Repositories.Entities.RecipeStep", "Step")
                        .WithMany("RobotStepTasks")
                        .HasForeignKey("StepId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotStepTask_StepId");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.User", b =>
                {
                    b.HasOne("AutoChefSystem.Repositories.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleId__4CA06362");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Location", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Robots");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Order", b =>
                {
                    b.Navigation("RobotOperationLogs");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Recipe", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RecipeSteps");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RecipeStep", b =>
                {
                    b.Navigation("RobotStepTasks");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Robot", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RobotOperationLogs");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.RobotType", b =>
                {
                    b.Navigation("Robots");
                });

            modelBuilder.Entity("AutoChefSystem.Repositories.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
